### ISSUE TITLE
Vagrunt name change from Vagrant to Viagrunts in the source code

### ISSUE THREAD

**Issue by andreasrosdal** [viagrunts/viagrunts#1]
Vagrunt name change from Vagrant to Viagrunts in the source code. The command shall be:

**viagrunts up**

**Comment by slyall** [comment]
Just a comment that the name might not be significant different from vagrant. In the past forks that only slightly changed the name have had to rename later.

Much easier to get the name right from the start.

**Comment by andreasrosdal** [comment]
New name: Viagrunts

**Comment by guillemj** [comment]
Perhaps snatch the organization name matching the project name too, before it's too late? To avoid confusion and/or possible trademark issues too.

**Comment by andreasrosdal** [comment]
It is Vagrunts all the way down now.

https://github.com/viagrunts/viagrunts

**Comment by AdamWill** [comment]
19,434 case-insensitive "vagrant"s in the source. that's gonna be fun!
